name: 🚀 Deploy to Cloudflare

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: ⬣ Lint & Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - run: pnpm install --prefer-offline --frozen-lockfile
            - name: Run oxlint
              run: pnpm run lint --format=github
            - name: Run oxfmt
              run: pnpm run fmt:check

    typecheck:
        name: 🔎 Type check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  cache: "pnpm"
            - run: pnpm install --prefer-offline --frozen-lockfile
            - run: pnpm run typecheck

    knip:
        name: ✂️ Knip - Check unused code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  cache: "pnpm"
            - run: pnpm install --prefer-offline --frozen-lockfile
            - run: pnpm run knip

    # test:
    #   name: ⚡ Tests
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v4
    #     - uses: pnpm/action-setup@v4
    #     - uses: actions/setup-node@v4
    #       with:
    #         node-version-file: "package.json"
    #         cache: "pnpm"
    #     - run: pnpm install --prefer-offline --frozen-lockfile
    #     - run: pnpm run test

    deploy:
        name: 📦 Deploy
        needs: [lint, typecheck, knip]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  cache: "pnpm"
            - run: pnpm install --prefer-offline --frozen-lockfile
            - run: pnpm run build
            - uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
